# Generated by Django 5.0.6 on 2026-05-22 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('expositor', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('clave_resultados', models.CharField(blank=True, max_length=64, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('texto', models.TextField()),
                ('seccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('escala', 'Escala'), ('abierta', 'Abierta')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluacion.actividad')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-enviada_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_abiertas', to='evaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta abierta',
                'verbose_name_plural': 'Respuestas abiertas',
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('NA', 'No Aplica'), ('MB', 'Muy Bueno'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente'), ('MD', 'Muy Deficiente')], max_length=2)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_escala', to='evaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de escala',
                'verbose_name_plural': 'Respuestas de escala',
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
