# Generated by Django 6.0.5 on 2026-05-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='cedula',
            new_name='correo',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='apellidos',
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('actividad', 'correo')},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pantalla',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('escala', 'Escala'),
                    ('abierta', 'Abierta'),
                    ('condicional', 'Condicional'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='respuestaescala',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RespuestaCondicional',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'opcion',
                    models.CharField(
                        choices=[
                            ('SI', 'Sí'),
                            ('PARCIAL', 'Parcialmente'),
                            ('NO', 'No'),
                        ],
                        max_length=10,
                    ),
                ),
                ('justificacion', models.TextField(blank=True)),
                (
                    'evaluacion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='respuestas_condicionales',
                        to='evaluacion.evaluacion',
                    ),
                ),
                (
                    'pregunta',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='evaluacion.pregunta',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Respuesta condicional',
                'verbose_name_plural': 'Respuestas condicionales',
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
